### ISSUE TITLE
DOB being stored improperly

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#125]
When registering for an event, I fill out my date of birth (January 3rd, 1984), however the database saves as 1984-02-03

<img width="569" alt="Screen Shot 2020-09-09 at 4 12 42 PM" src="https://user-images.githubusercontent.com/64417502/92648671-c538ea80-f2b7-11ea-9021-be0373425b38.png">

This is causing the PantryTrak Match Interface to not align the DOB's properly:

![image (15)](https://user-images.githubusercontent.com/64417502/92648698-d2ee7000-f2b7-11ea-9f4e-580026fd5aa1.png)

**Comment by sarath-yerra** [comment]
@thompson2091 FYI Sean Implemented this way 

seanlawrenz commented 7 days ago
The issue seems to be that some browsers are able to create a new date and convert to ISO and some are not.

This will split the date into it's individual sections (year, month, number of day in month) and create the ISO that way.

We should still revisit this as I've found some issues with data persisting. The DOB comes back as '1984-08-16' but the client does not see that as valid. That is good for us now as this fix is fragile and only works for '08 / 16 / 1984'. But this should stop failing on mobile devices.

**Comment by seanlawrenz** [comment]
@thompson2091 The format YYYY-MM-DD is how the data base wants it stored. [I don't have the original task but here is an issue illustrating the format](https://github.com/midohiofoodbank/freshtrak-client/issues/96)

**Comment by thompson2091** [comment]
@seanlawrenz sorry for the confusion - the issue isn't with the format of the date - rather, it is an issue with the month being incremented by 1 when being inserted.  I inserted my DOB as January 3rd, 1984 (1984-01-03), but the database stored 1984-02-03

The next image shows an example of an actual user that we were able to match within PantryTrak, but the DOB stored in FreshTrak was +1 month:

![92648698-d2ee7000-f2b7-11ea-9f4e-580026fd5aa1](https://user-images.githubusercontent.com/64417502/92671117-74d78200-f2e3-11ea-8815-1a8f3a904ac0.png)
