### ISSUE TITLE
Add Returning Visitor Login GTM Event

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#146]
Currently, when a user attempts to register for an event, we fire the following events to Google Tag Manager:

1) modal-open
2) guest-login (OR facebook-login, depending on method selected)
3) reservation (on successful reservation)

I would like to fire a different event when a returning visitor is logging in.  Instead of firing guest-login, could we instead fire a new event called "returning-visitor-login".  In this case, the sequence would be as follows:

1) modal-open (I am open to a discussion on whether we should fire modal-open, or instead fire a new event every time somebody clicks Register Now on the /events/list page)
2) returning-visitor-login
3) reservation (on successful reservation)

The code snippet that would need to be implemented is as follows:

`
TagManager.dataLayer({ dataLayer: { event: "returning-visitor-login" } })
`

**Comment by maheshkurma** [comment]
As per my knowledge, 
1. guest-login always creates a new user, so no returning visitor will be for guest.
2. we can fire returning-visitor-login for only facebook returning users, and also since fb users are our customers do u want to fire event as _returning-customer-login_ .

Presently in users table user_type is persisted as **guest** for guest users and **customer** for facebook users

There would be three scenarios we can fire events as follows:
Always Guest Login - 
modal-open (fire modal-open, somebody clicks Register Now) > guest-login > reservation

First time Facebook Login - 
modal-open (fire modal-open, somebody clicks Register Now) > facebook-login > reservation

Returning Facebook User - 
modal-open (fire modal-open, somebody clicks Register Now) > returning-customer-login > reservation

**Comment by thompson2091** [comment]
@maheshkurma yes, I agree with you.  Let's use **returning-customer-login** in the event of a returning user being automatically logged in.  I also understand that, currently, this will only fire for facebook returning customers.  I agree with the 3 scenarios that you outlined:


Always Guest Login -
modal-open (fire modal-open, somebody clicks Register Now) > guest-login > reservation

First time Facebook Login -
modal-open (fire modal-open, somebody clicks Register Now) > facebook-login > reservation

Returning Facebook User -
modal-open (fire modal-open, somebody clicks Register Now) > returning-customer-login > reservation
