### ISSUE TITLE
Improve Registration Blocking Controls and Messaging

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#77]
User Story: I am a food pantry/foodbank and I am posting links to my events to collect RSVPs. I post the link on Facebook/email/my website and don't control when people go to it. However, I don't want to get additional RSVPs after a number of conditions:
- We have passed the "Published End datetime" (the service date is no longer being published) event_dates.published_end_datetime
- The Service Date is at capacity (reserved >= capacity) event_dates.reserved & event_dates.capacity
- It is too early to take RSVPs (The service date is not yet being published) event_dates.published_date

Background and context: This Feature request is based on feedback and learning from the first two weeks of FreshTrak usage. Most of the traffic on the site is based around links being posted directly to registration page. We need to improve information on that page (see issue #76 ) and also screen for the above conditions and provide feedback if those conditions are tripped.

Requirements:
- When the page is loading, check the three conditions listed above
- If any of those conditions mean that the user should not have access to the RSVP page, tell them why they do not have access to the RSVP page, and give them a link back to the home page.
- If any of those conditions are not tripped, they can register as usual.

**Comment by davidpickering** [comment]
@PhilNorman2 could you evaluate this Issue and check if we have the needed information coming out of the agencies API call?

**Comment by PhilNorman2** [comment]
@davidpickering  All of this is available through the event_date API so there should not be a need to call the agencies API.  The requests coming in to the client are in the form of:

https://beta.freshtrak.com/events/register/7605. (where 7605 is the event_date id of the registration)

I would recommend that the UI then calls the event_date API with a URL in the form of:

https://pantry-finder-api.beta.freshtrak.com/api/event_dates/7605

- If an event_date JSON object is returned and  event_date.capacity <= 0 the UI should display the appropriate error message.

Based on event_date scopes the following conditions will not return an event_date in the response.  The API should return a 404 HTTP status code with the message "record not found" in these cases.  The UI should display the appropriate error message (something like Event_date is no longer valid):

- Current datetime is > event_date.end_datetime
- Current Date > event_date.published_date_key
- Current Date < event_date.event_date_key
- event_date.status_id <> 1
- event.publishes_dates == false

We currently do not have a way to indicate which of these conditions has occurred.  I would guess in nearly all cases it would be because the event_date.end_datetime has passed.  

Also it just occured to me that the event_date.event_date_key might be redundant now that we have the end_datetime scope.

**Comment by PhilNorman2** [comment]
> The Service Date is at capacity (reserved >= capacity) event_dates.reserved & event_dates.capacity

@davidpickering I discussed this with @maheshkurma.  Currently the client UI does not check the value of event.hour.open_slots because the data is not current.  Instead the registration-api checks this based on the Reservations table , Reservation.where(event_date_id: event_date_id).count.  If there is a capacity error the user would get it after submitting the registration not before.  This should continue to work regardless of whether the registration request comes from the freshtrak client directly or a link in a text message.  Mahesh said Nikhil had worked on this piece, if you have further questions.

**Comment by PhilNorman2** [comment]
>could you evaluate this Issue and check if we have the needed information coming out of the agencies API call?

So to circle back around to this question.  In the case where the user is getting to the registration page through the freshtrak-client, the appropriate event_dates should be displayed and no further information is needed.  However, unless the UI can determine whether the registration request came in through the freshtrak-client or a link in a text message or facebook post, the UI should call the event_date API with the event_date in either case.

If in the future, if the open_slots information is accurate and the capacity could be determined before the registration is submitted, then the client would need to call the event_date API to get that information (or it might be possible to aggregate that information in the event_date object in the agencies API response through the associations if the UI can determine the registration request came in through the freshtrak-client and ergo the agencies API).

**Comment by davidpickering** [comment]
Closed by #126 added V1 checking of the event date information. Prevents registration after the published_end_datetime, if the event is over capacity (reserved >= capacity).
